config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users, only: [:create]
  resources :flights, only: [:index, :new, :create, :edit, :update]

  get 'sign-out' => 'sessions#destroy'
end

app/models/airplane.rb
class Airplane < ActiveRecord::Base

has_many :flights
has_many :destinations, through: :flights
validates :serial_number, uniqueness: true

  def plane_information
    "#{self.airline} #{self.manufacturer} #{self.serial_number}"
  end
end

app/models/destination.rb
class Destination < ActiveRecord::Base
has_many :flights
has_many :airplanes, through: :flights

validates :city, uniqueness: {scope: :state}

  def location
    "#{self.city}, #{self.state}"
  end
end

app/models/flight.rb
class Flight < ActiveRecord::Base
belongs_to :airplane
belongs_to :destination

validate :past_departures

  def past_departures
    if departure_date < Time.now
      errors[:departure_date] << "can't be in the past"
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
    @flights = Flight.all
  end

  def new
    @flight = Flight.new
  end

  def create
    @flight = Flight.new(flight_params)
    if @flight.save
      redirect_to flights_path
      flash[:notice] = "Successfully created flight to #{@flight.destination.location}"
    else
      flash[:notice] = "Error creating flight"
      render :new
    end
  end

  def edit
    @flight = Flight.find(params[:id])
  end

  def update
    @flight = Flight.find(params[:id])
    if @flight.update(flight_params)
      redirect_to flights_path, notice: 'Flight successfully updated'
    else
      render :edit
    end
  end

  private

  def flight_params
    params.require(:flight).permit(:departure_date, :airplane_id, :destination_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    session.clear
    redirect_to root_path, notice: 'Successfully signed out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    user = User.new(user_params)
    user.save!
    session[:user_id] = user.id
    redirect_to flights_path
  end

private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flights/edit.html.erb
<%= form_for @flight do |f| %>
  <% if @flight.errors.any? %>
    <% @flight.errors.full_messages.each do |message|  %>
      <%= message %>
    <% end %>
  <% end %>

  <%= f.label :airplane_id, 'Airplane' %>
  <%= f.collection_select(:airplane_id, Airplane.all, :id, :plane_information) %>

  <%= f.submit %>

<% end %>

app/views/flights/index.html.erb
List of Flights
<%= link_to 'Sign out', sign_out_path %>
<%= link_to 'New Flight', new_flight_path %>


<h1>Welcome to the Flight Scheduler</h1>
<% @flights.each do |flight| %>
<%= link_to "#{flight.airplane.plane_information} to #{ flight.destination.location }", edit_flight_path(flight) %>
<h2>List of Flights</h2>
<% end %>

app/views/flights/new.html.erb
<%= form_for @flight do |f| %>
  <% if @flight.errors.any? %>
    <% @flight.errors.full_messages.each do |message|  %>
      <%= message %>
    <% end %>
  <% end %>

  <%= f.label :airplane_id, 'Airplane' %>
  <%= f.collection_select(:airplane_id, Airplane.all, :id, :plane_information) %>

  <%= f.label :destination_id, 'Destination' %>
  <%= f.collection_select(:destination_id, Destination.all, :id, :location) %>

  <%= f.label :departure_date, "Departure Date" %>
  <%= f.date_field :departure_date %>

  <%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BamAssociationsAndValidations</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= notice %>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Please register below</h1>

<%= form_for @user, html: {class: 'sign-up-form'} do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <br />

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br />

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br />

  <%= f.submit 'Sign up' %>
<% end %>